# Generated by Django 6.1 on 2026-08-17 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('PENDING_INFORMATION', 'Pending Information'), ('RETURNED', 'Returned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED_TO_ED', 'Forwarded to ED'), ('FORWARDED_TO_CEO', 'Forwarded to CEO'), ('CEO_APPROVED', 'CEO Approved'), ('CEO_REJECTED', 'CEO Rejected'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('ed_received_at', models.DateTimeField(blank=True, null=True)),
                ('ed_forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('ceo_received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('destination_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_requests', to='departments.department')),
                ('originating_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_requests', to='departments.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
