# Generated by Django 6.1 on 2026-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_document',
            field=models.FileField(blank=True, null=True, upload_to='requests/%Y/%m/'),
        ),
    ]
