# Generated by Django 6.1 on 2026-08-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_request_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_document',
            field=models.FileField(blank=True, null=True, upload_to='request_documents/'),
        ),
    ]
